export interface AttendanceEntry {
    Id: number,
    Amount: number,
    ApprovalLevel: number,
    ApprovalStatus: number,
    ApprovedBy: number,
    ApprovedDate: string,
    BlockId: number,
    BranchId: number,
    Category: number,
    CompanyId: number,
    DateAssigned: string,
    DateWorked: string,
    EmployeeId: number,
    FinancialYearId: number,
    FloorId: number,
    LoginTime: string,
    LogoutTime: string,
    OverTime: number,
    OverTimeAmount: number,
    ProjectId: number,
    Remarks: string,
    UnitId: number,
    Work: number,
}