export interface AttendanceEntry {
    attendanceId: Number;
    employeeId: Number,
    projectId: Number,
    unitId: Number,
    blockId: Number,
    floorId: Number,
    companyId: Number,
    branchId: Number,
    financialYear_id: Number,
    dateWorked: Date,
    amount: Number,
    loginTime: Date,
    logoutTime: Date,
    work: Number,
    overTime: Number,
    overTimeAmount: Number,
    approvalStatus: Number,
    approvedDate: Date,
    category: Number,
    approvedBy: Number,
    remarks: String,
    approvalLevel: Number,
}