export interface AttendanceEntry {
    attendanceId: number;
    employeeId: number,
    projectId: number,
    unitId: number,
    blockId: number,
    floorId: number,
    companyId: number,
    branchId: number,
    financialYear_id: number,
    dateWorked: Date,
    amount: number,
    loginTime: Date,
    logoutTime: Date,
    work: number,
    overTime: number,
    overTimeAmount: number,
    approvalStatus: number,
    approvedDate: Date,
    category: number,
    approvedBy: number,
    remarks: String,
    approvalLevel: number,
}