export const SideNavbarMetadata = {
    "moduleId": "sidenavbar",
    "moduleName": "Sidenavbar",
    "serviceEndPoint": "BuildExeCRM/api/Menu"
}

export const SideNavigationMenu = {
    1000: { menuId: 1000, menuName: 'MASTER', route: '' },
    2000: { menuId: 2000, menuName: 'CRM', route: '' },
    3000: { menuId: 3000, menuName: 'MATERIAL MANAGEMENT', route: '' },
    4000: { menuId: 4000, menuName: 'HR AND LABOUR', route: '' },
    5000: { menuId: 5000, menuName: 'GENERAL ACCOUNTS', route: '' },
    6000: { menuId: 6000, menuName: 'PAYMENT AND RECEIPT', route: '' },
    7000: { menuId: 7000, menuName: 'DOCUMENT MANAGEMENT', route: '' },
    8000: { menuId: 8000, menuName: 'ESTIMATION', route: '' },
    9000: { menuId: 9000, menuName: 'USER MANAGEMENT', route: '' },
    1001: { menuId: 1001, menuName: 'Company', route: '/company' },
    1002: { menuId: 1002, menuName: 'Department', route: '/department' },
    1003: { menuId: 1003, menuName: 'Labour Work Rate Setting', route: '/labourworkratesetting' },
    1004: { menuId: 1004, menuName: 'Work Category', route: '/workcategory' },
    1005: { menuId: 1005, menuName: 'Financial Year Registration', route: '/financialyear' },
    1006: { menuId: 1006, menuName: 'Bank Account Registration', route: '/bankaccountregistration' },
    2001: { menuId: 2001, menuName: 'Master', route: '' },
    2002: { menuId: 2002, menuName: 'Enquiry', route: '' },
    2003: { menuId: 2003, menuName: 'Project', route: '' },
    2004: { menuId: 2004, menuName: 'Bill Generation', route: '' },
    2005: { menuId: 2005, menuName: 'Enquiry Mode', route: '/enquirymode' },
    2006: { menuId: 2006, menuName: 'Enquiry Status', route: '/enquirystatus' },
    2007: { menuId: 2007, menuName: 'Enquiry For', route: '/enquiryfor' },
    2008: { menuId: 2008, menuName: 'Marketing Team', route: '/team' },
    2009: { menuId: 2009, menuName: 'Consultancy Work', route: '/consultancywork' },
    2010: { menuId: 2010, menuName: 'Floor Registration', route: '/floor' },
    2011: { menuId: 2011, menuName: 'Block Registration', route: '/block' },
    2012: { menuId: 2012, menuName: 'Assign Block Floors', route: '/assignblockfloors' },
    2013: { menuId: 2013, menuName: 'Enquiry', route: '/enquiry' },
    2014: { menuId: 2014, menuName: 'Followup', route: '/followup' },
    2015: { menuId: 2015, menuName: 'Project registration', route: '/project' },
    2016: { menuId: 2016, menuName: 'Project Booking', route: '/projectbooking' },
    2017: { menuId: 2017, menuName: 'Project Status', route: '/projectstatus' },
    2018: { menuId: 2018, menuName: 'Part bill', route: '' },
    2019: { menuId: 2019, menuName: 'Part bill Approval', route: '' },
    2020: { menuId: 2020, menuName: 'Percentage wise bill', route: '' },
    2021: { menuId: 2021, menuName: 'Percentage wise bill approval', route: '' },
    2022: { menuId: 2022, menuName: 'Additional bill', route: '/additionalbill' },
    2023: { menuId: 2023, menuName: 'Additional bill approval', route: '/additionalbillapproval' },
    2024: { menuId: 2024, menuName: 'Stage Completion Bill', route: '' },
    3001: { menuId: 3001, menuName: 'Master', route: '' },
    3002: { menuId: 3002, menuName: 'Purchase', route: '' },
    3003: { menuId: 3003, menuName: 'Material Transfer', route: '' },
    3004: { menuId: 3004, menuName: 'Material Issue', route: '' },
    3005: { menuId: 3005, menuName: 'Quotation', route: '' },
    3006: { menuId: 3006, menuName: 'Unit Registration', route: '/unitregistration' },
    3007: { menuId: 3007, menuName: 'Material Brand Registration', route: '/materialbrandregistration' },
    3008: { menuId: 3008, menuName: 'Material Category Registration', route: '/materialcategoryregistration' },
    3009: { menuId: 3009, menuName: 'Material Registration', route: '/materialregistration' },
    3010: { menuId: 3010, menuName: 'Supplier Registration', route: '/supplierregistration' },
    3011: { menuId: 3011, menuName: 'Indent Creation', route: '/materialindentcreation' },
    3012: { menuId: 3012, menuName: 'Indent Approval', route: '/materialindentapproval' },
    3013: { menuId: 3013, menuName: 'Purchase Order', route: '/materialpurchaseorder' },
    3014: { menuId: 3014, menuName: 'Purchase Order Approval', route: '/materialpurchaseorderapproval' },
    3015: { menuId: 3015, menuName: 'Stock entry', route: '/materialstockentry' },
    3016: { menuId: 3016, menuName: 'Stock Entry approval ', route: '/materialstockentryapproval' },
    3017: { menuId: 3017, menuName: 'Direct stock entry', route: '/materialdirectstockentry' },
    3018: { menuId: 3018, menuName: 'Direct stock entry approval', route: '/materialdirectstockentryapproval' },
    3031: { menuId: 3031, menuName: 'Damage Stock Entry', route: '/materialdamagestock' },
    3032: { menuId: 3032, menuName: 'Damage Stock Entry Approval', route: '/materialdamagestockapproval' },
    3020: { menuId: 3020, menuName: 'Material Purchase Return', route: '/materialpurchasereturn' },
    3021: { menuId: 3021, menuName: 'Material Purchase Return Approval', route: '/materialpurchasereturnapproval' },
    3022: { menuId: 3022, menuName: 'Material Transfer Request', route: '/materialtransferrequest' },
    3023: { menuId: 3023, menuName: 'Material Transfer  Approval', route: '/materialtransferrequestapproval' },
    3024: { menuId: 3024, menuName: 'Material Recieve', route: '/materialreceived' },
    3025: { menuId: 3025, menuName: 'Material Recieve Approval', route: '/materialreceivedapproval' },
    3026: { menuId: 3026, menuName: 'Material Issue', route: '/materialusage' },
    3027: { menuId: 3027, menuName: 'Material Issue Approval', route: '/materialusageapproval' },
    3028: { menuId: 3028, menuName: 'Quotation Creating', route: '/materialquotation' },
    3029: { menuId: 3029, menuName: 'Base Rate Feeding', route: '/quotationbaseratefeeding' },
    3030: { menuId: 3030, menuName: 'Quotation Approval', route: '/materialquotationapproval' },
    1007: { menuId: 1007, menuName: 'Module Setting', route: '/modulesetting' },
    6001: { menuId: 6001, menuName: 'General', route: '' },
    6002: { menuId: 6002, menuName: 'Receipts', route: '' },
    6003: { menuId: 6003, menuName: 'Payments', route: '' },
    6004: { menuId: 6004, menuName: 'Site Manager', route: '' },
    6005: { menuId: 6005, menuName: 'Cheque Clearence', route: '' },
    6006: { menuId: 6006, menuName: 'Voucher Entry', route: '' },
    6007: { menuId: 6007, menuName: 'Bill Receipt', route: '' },
    6008: { menuId: 6008, menuName: 'Stage Receipt', route: '' },
    6009: { menuId: 6009, menuName: 'Client Advance', route: '' },
    6010: { menuId: 6010, menuName: 'Material Supplier Advance', route: '/materialsupplieradvance' },
    6011: { menuId: 6011, menuName: 'Material Supplier Payment', route: '/materialsupplierpayment' },
    6012: { menuId: 6012, menuName: 'Site Manager Transaction', route: '' },
    7001: { menuId: 7001, menuName: 'Document Group', route: '' },
    7002: { menuId: 7002, menuName: 'Document Type', route: '' },
    7003: { menuId: 7003, menuName: 'Document Upload', route: '' },
    8001: { menuId: 8001, menuName: 'Work Type', route: '/worktype' },
    8002: { menuId: 8002, menuName: 'Specification Registration', route: '/specification' },
    8003: { menuId: 8003, menuName: 'Template Registration', route: '/template' },
    8004: { menuId: 8004, menuName: 'Project Specification', route: '/projectspecification' },
    9001: { menuId: 9001, menuName: 'User Group', route: '/usergroup' },
    9002: { menuId: 9002, menuName: 'User', route: '/user' },
    9003: { menuId: 9003, menuName: 'Approval Level', route: '/levelsetting' },
    9004: { menuId: 9004, menuName: 'User Approval Level Setting', route: '/approvelevel' },
    9005: { menuId: 9005, menuName: 'User Previlege ', route: '/userprevilege' }
  }
